[versions]
androidGradlePlugin = "8.6.1"
androidxActivity = "1.10.1"
androidxAppCompat = "1.7.1"
androidxComposeBom = "2024.09.02"
androidxComposeCompiler = "1.4.7"
androidxCore = "1.16.0"
androidxCoreSplashscreen = "1.0.1"
androidxEspresso = "3.6.1"
androidxLifecycle = "2.8.7"                # Newer versions require kotlin 2+
androidxNavigation = "2.8.9"               # Newer versions require kotlin 2+
androidxWindowManager = "1.4.0"
androidXbrowser = "1.8.0"
coil = "2.3.0"
junit4 = "4.13.2"
junitParams = "1.1.1"
kotlin = "1.8.21"
kotlinxCoroutines = "1.7.3"
kotlinxSerializationJson = "1.6.3"         # Newer versions require kotlin 2+
kotlinxCollectionsImmutable = "0.3.7"
okhttpBom = "4.10.0"
rebugger = "1.0.0-rc03"
retrofit = "2.11.0"
retrofitKotlinxSerializationJson = "0.8.0"
mockk = "1.13.16"
assertj-core = "3.15.0"
dcui = "2.3.0"
robolectric = "4.14.1"
composeLint = "1.4.1"
lifecycleRuntimeKtx = "2.8.7"              # Newer versions require kotlin 2+
junit = "1.2.1"
material = "1.12.0"
dokka = "2.0.0"
playServicesCodeScanner = "16.1.0"
androidxHiltNavigationCompose = "1.2.0"
hilt = "2.51.1"
activity = "1.10.1"
constraintlayout = "2.2.1"
mavenPublish = "0.31.0"
kover = "0.9.1"

roktUxHelper = "0.2.0"
sdkVersionCode = "79"
roborazzi = "1.43.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-window-manager = { module = "androidx.window:window", version.ref = "androidxWindowManager" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidXbrowser" }
coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-kt-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-kt-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
coil-test = { group = "io.coil-kt", name = "coil-test", version.ref = "coil" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
junit-params = { group = "pl.pragmatists", name = "JUnitParams", version.ref = "junitParams" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttpBom" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp" }
okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver" }
rebugger = { module = "io.github.theapache64:rebugger", version.ref = "rebugger" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-kotlin-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinxSerializationJson" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj-core" }
dcui-schema = { group = "com.rokt.internal.network.types", name = "dcui-schema", version.ref = "dcui" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
dokka-android = { group = "org.jetbrains.dokka", name = "android-documentation-plugin", version.ref = "dokka" }
play-services-code-scanner = { module = "com.google.android.gms:play-services-code-scanner", version.ref = "playServicesCodeScanner" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }


# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-lint-checks = { group = "com.slack.lint.compose", name = "compose-lint-checks", version.ref = "composeLint" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
maven-publishPlugin = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "mavenPublish" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { group = "io.github.takahirom.roborazzi", name = "roborazzi-compose", version.ref = "roborazzi" }
roborazzi-junit-rule = { group = "io.github.takahirom.roborazzi", name = "roborazzi-junit-rule", version.ref = "roborazzi" }

[bundles]
retrofit = ["retrofit-core", "retrofit-kotlin-serialization"]
mockk = ["mockk-android", "mockk-agent"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }

# Plugins defined by this project
rokt-android-application = { id = "rokt.android.application" }
rokt-android-application-compose = { id = "rokt.android.application.compose" }
rokt-android-library = { id = "rokt.android.library" }
rokt-android-library-compose = { id = "rokt.android.library.compose" }
rokt-android-library-publish = { id = "rokt.android.library.publish" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
